### ISSUE TITLE
[BUG] Opening a locked conversation from a notification crashes the app

### ISSUE THREAD

**Issue by Terrariadlc** [Mino260806/MessengerPro#21]
Release: v1.0.4
Device: Xiaomi mi note 10 lite (toco)
Android: 13
ROM: EvolutionX
LSposed error: 
```
07-10 19:09:13.537  4298  4340 W WindowManager: Failed looking up window session=null callers=com.android.server.wm.WindowManagerService.addWindow:1510 com.android.server.wm.Session.addToDisplayAsUser:214 android.view.IWindowSession$Stub.onTransact:642 
07-10 19:09:13.537  4298  4340 W WindowManager: Attempted to add window with token that is not a window: null.  Aborting.
07-10 19:09:13.539 24319 24319 E AndroidRuntime: FATAL EXCEPTION: main
07-10 19:09:13.539 24319 24319 E AndroidRuntime: Process: com.facebook.orca, PID: 24319
07-10 19:09:13.539 24319 24319 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1325)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:421)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at tn.amin.mpro2.ui.BlackOverlay.lambda$on$0(BlackOverlay.java:29)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at tn.amin.mpro2.ui.BlackOverlay$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:4)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7926)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-10 19:09:13.539 24319 24319 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
No other facebook/meta apps are present

**Comment by Mino260806** [comment]
Issue fixed. Will take effect in next release
Thanks for reporting!
