### ISSUE TITLE
Cant Reinstall Messenger And Facebook

### ISSUE THREAD

**Issue by phoenixpalmer** [Mino260806/MessengerPro#52]
so i used messenger pro and i felt like i didnt really need it anymore so i uninstalled it and tried updating messenger but that didnt work so i uninstalled it and tried to install but it either said doesnt work or incompatible, this is also the same with facebook, i tried deleting data of google play store, restarting my device, switching accounts, deleting updates of play store nothing worked, please someone help me out thanks!

**Comment by Mino260806** [comment]
Can you try uninstalling messenger using adb (google how to execute adb commands) with this command ?
```
adb uninstall com.facebook.orca
``` 

If it still doesn't work, please show the output of this command
```
adb shell pm list packages
```
Or try to install messenger from adb and show the error output
```
adb install messenger.apk
```

**Comment by Mope04** [comment]
> Can you try uninstalling messenger using adb (google how to execute adb commands) with this command ?
> 
> ```
> adb uninstall com.facebook.orca
> ```
> 
> If it still doesn't work, please show the output of this command
> 
> ```
> adb shell pm list packages
> ```
> 
> Or try to install messenger from adb and show the error output
> 
> ```
> adb install messenger.apk
> ```

running adb uninstall com.facebook.orca, shows it is successful, but after uninstalling facebook, and installing messenger pro, it shows that I am unable to install facebook.

Running adb shell pm list packages. 
Result: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:14999 android.app.ActivityManager.handleIncomingUser:4805 com.android.server.pm.PackageManagerShellCommand.translateUserId:3517
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2680)
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14999)
        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4805)
        at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3517)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:969)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:865)
        at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:724)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:226)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7071)
        at android.os.Binder.shellCommand(Binder.java:1085)
        at android.os.Binder.onTransact(Binder.java:903)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7055)
        at android.os.Binder.execTransactInternal(Binder.java:1321)
        at android.os.Binder.execTransact(Binder.java:1280).

Finally, installing messengerpro via adb (adb shell pm install /data/user/0/messenger416-pie-noroot.apk) , shows the following result
Result: 

Error: Unable to open file: /data/user/0/messenger416-pie-noroot.apk
Error: Unable to open file: /data/user/0/pakagename/cache/messenger416-pie-noroot.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: /data/user/0/pakagename/cache/messenger416-pie-noroot.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: /data/user/0/pakagename/cache/messenger416-pie-noroot.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:625)
        at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1480)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1446)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:238)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7071)
        at android.os.Binder.shellCommand(Binder.java:1085)
        at android.os.Binder.onTransact(Binder.java:903)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7055)
        at android.os.Binder.execTransactInternal(Binder.java:1321)
        at android.os.Binder.execTransact(Binder.java:1280)
